# Generated by Django 4.1.1 on 2022-11-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioGasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=222)),
                ('date', models.DateField()),
            ],
        ),
    ]
