# Generated by Django 4.1.1 on 2022-11-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioGasApp', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Services',
        ),
    ]
